#!/bin/bash

if [ -z "$1" ]; then
    echo Filename:
    read MKP
    cd  /home/mgg/pythonStudy
    touch ./${MKP}.py
    chmod u+x ${MKP}.py
    vim ${MKP}.py
else    
    cd /home/mgg/pythonStudy
    touch ./${1}.py
    chmod u+x ${1}.py
    vim ${1}.py
fi
