#!/bin/bash

if [ -z "$1" ]; then
    echo Filename:
    read MKP
    cd  /home/maciek/workspace/perlStudy
    touch ./${MKP}.pl
    chmod u+x ${MKP}.pl
    echo -e "#!/usr/bin/perl\n" > ${MKP}.pl
    vim ${MKP}.pl
else    
    cd /home/maciek/workspace/perlStudy
    touch ./${1}.pl
    chmod u+x ${1}.pl
    echo -e "#!/usr/bin/perl\n" > ${MKP}.pl
    vim ${1}.pl
fi
